// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `Player.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef __Player_h__
#define __Player_h__

#include <IceUtil/PushDisableWarnings.h>
#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/StreamHelpers.h>
#include <Ice/Proxy.h>
#include <Ice/GCObject.h>
#include <Ice/AsyncResult.h>
#include <Ice/Incoming.h>
#include <IceUtil/ScopedArray.h>
#include <IceUtil/Optional.h>
#include <Ice/StreamF.h>
#include <IceUtil/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 306
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 3
#       error Ice patch level mismatch!
#   endif
#endif

namespace IceProxy
{

namespace MP3Player
{

class Player;
void __read(::IceInternal::BasicStream*, ::IceInternal::ProxyHandle< ::IceProxy::MP3Player::Player>&);
::IceProxy::Ice::Object* upCast(::IceProxy::MP3Player::Player*);

}

}

namespace MP3Player
{

class Player;
::Ice::Object* upCast(::MP3Player::Player*);
typedef ::IceInternal::Handle< ::MP3Player::Player> PlayerPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::MP3Player::Player> PlayerPrx;
void __patch(PlayerPtr&, const ::Ice::ObjectPtr&);

}

namespace MP3Player
{

typedef ::std::vector< ::Ice::Byte> File;

}

namespace MP3Player
{

class Callback_Player_getInvocationCount_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_Player_getInvocationCount_Base> Callback_Player_getInvocationCountPtr;

class Callback_Player_addFile_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_Player_addFile_Base> Callback_Player_addFilePtr;

class Callback_Player_deleteFile_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_Player_deleteFile_Base> Callback_Player_deleteFilePtr;

class Callback_Player_deleteDirectory_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_Player_deleteDirectory_Base> Callback_Player_deleteDirectoryPtr;

class Callback_Player_getFileLength_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_Player_getFileLength_Base> Callback_Player_getFileLengthPtr;

class Callback_Player_getFilesByRegex_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_Player_getFilesByRegex_Base> Callback_Player_getFilesByRegexPtr;

class Callback_Player_getFile_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_Player_getFile_Base> Callback_Player_getFilePtr;

}

namespace IceProxy
{

namespace MP3Player
{

class Player : virtual public ::IceProxy::Ice::Object
{
public:

    void getInvocationCount(const ::std::string& __p_s)
    {
        getInvocationCount(__p_s, 0);
    }
    void getInvocationCount(const ::std::string& __p_s, const ::Ice::Context& __ctx)
    {
        getInvocationCount(__p_s, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_getInvocationCount(const ::std::string& __p_s, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_getInvocationCount(__p_s, 0, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent));
    }
    ::Ice::AsyncResultPtr
    begin_getInvocationCount(const ::std::string& __p_s, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_getInvocationCount(__p_s, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_getInvocationCount(const ::std::string& __p_s, const ::Ice::Context& __ctx, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_getInvocationCount(__p_s, &__ctx, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_getInvocationCount(const ::std::string& __p_s, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_getInvocationCount(__p_s, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
#endif

    ::Ice::AsyncResultPtr begin_getInvocationCount(const ::std::string& __p_s)
    {
        return begin_getInvocationCount(__p_s, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_getInvocationCount(const ::std::string& __p_s, const ::Ice::Context& __ctx)
    {
        return begin_getInvocationCount(__p_s, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_getInvocationCount(const ::std::string& __p_s, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getInvocationCount(__p_s, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getInvocationCount(const ::std::string& __p_s, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getInvocationCount(__p_s, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getInvocationCount(const ::std::string& __p_s, const ::MP3Player::Callback_Player_getInvocationCountPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getInvocationCount(__p_s, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getInvocationCount(const ::std::string& __p_s, const ::Ice::Context& __ctx, const ::MP3Player::Callback_Player_getInvocationCountPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getInvocationCount(__p_s, &__ctx, __del, __cookie);
    }

    void end_getInvocationCount(const ::Ice::AsyncResultPtr&);
    
private:

    void getInvocationCount(const ::std::string&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_getInvocationCount(const ::std::string&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    void addFile(const ::MP3Player::File& __p_f, const ::std::string& __p_name)
    {
        addFile(__p_f, __p_name, 0);
    }
    void addFile(const ::MP3Player::File& __p_f, const ::std::string& __p_name, const ::Ice::Context& __ctx)
    {
        addFile(__p_f, __p_name, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_addFile(const ::MP3Player::File& __p_f, const ::std::string& __p_name, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_addFile(__p_f, __p_name, 0, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent));
    }
    ::Ice::AsyncResultPtr
    begin_addFile(const ::MP3Player::File& __p_f, const ::std::string& __p_name, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_addFile(__p_f, __p_name, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_addFile(const ::MP3Player::File& __p_f, const ::std::string& __p_name, const ::Ice::Context& __ctx, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_addFile(__p_f, __p_name, &__ctx, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_addFile(const ::MP3Player::File& __p_f, const ::std::string& __p_name, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_addFile(__p_f, __p_name, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
#endif

    ::Ice::AsyncResultPtr begin_addFile(const ::MP3Player::File& __p_f, const ::std::string& __p_name)
    {
        return begin_addFile(__p_f, __p_name, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_addFile(const ::MP3Player::File& __p_f, const ::std::string& __p_name, const ::Ice::Context& __ctx)
    {
        return begin_addFile(__p_f, __p_name, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_addFile(const ::MP3Player::File& __p_f, const ::std::string& __p_name, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_addFile(__p_f, __p_name, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_addFile(const ::MP3Player::File& __p_f, const ::std::string& __p_name, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_addFile(__p_f, __p_name, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_addFile(const ::MP3Player::File& __p_f, const ::std::string& __p_name, const ::MP3Player::Callback_Player_addFilePtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_addFile(__p_f, __p_name, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_addFile(const ::MP3Player::File& __p_f, const ::std::string& __p_name, const ::Ice::Context& __ctx, const ::MP3Player::Callback_Player_addFilePtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_addFile(__p_f, __p_name, &__ctx, __del, __cookie);
    }

    void end_addFile(const ::Ice::AsyncResultPtr&);
    
private:

    void addFile(const ::MP3Player::File&, const ::std::string&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_addFile(const ::MP3Player::File&, const ::std::string&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    void deleteFile(const ::std::string& __p_name)
    {
        deleteFile(__p_name, 0);
    }
    void deleteFile(const ::std::string& __p_name, const ::Ice::Context& __ctx)
    {
        deleteFile(__p_name, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_deleteFile(const ::std::string& __p_name, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_deleteFile(__p_name, 0, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent));
    }
    ::Ice::AsyncResultPtr
    begin_deleteFile(const ::std::string& __p_name, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_deleteFile(__p_name, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_deleteFile(const ::std::string& __p_name, const ::Ice::Context& __ctx, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_deleteFile(__p_name, &__ctx, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_deleteFile(const ::std::string& __p_name, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_deleteFile(__p_name, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
#endif

    ::Ice::AsyncResultPtr begin_deleteFile(const ::std::string& __p_name)
    {
        return begin_deleteFile(__p_name, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_deleteFile(const ::std::string& __p_name, const ::Ice::Context& __ctx)
    {
        return begin_deleteFile(__p_name, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_deleteFile(const ::std::string& __p_name, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_deleteFile(__p_name, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_deleteFile(const ::std::string& __p_name, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_deleteFile(__p_name, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_deleteFile(const ::std::string& __p_name, const ::MP3Player::Callback_Player_deleteFilePtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_deleteFile(__p_name, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_deleteFile(const ::std::string& __p_name, const ::Ice::Context& __ctx, const ::MP3Player::Callback_Player_deleteFilePtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_deleteFile(__p_name, &__ctx, __del, __cookie);
    }

    void end_deleteFile(const ::Ice::AsyncResultPtr&);
    
private:

    void deleteFile(const ::std::string&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_deleteFile(const ::std::string&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    void deleteDirectory(const ::std::string& __p_name)
    {
        deleteDirectory(__p_name, 0);
    }
    void deleteDirectory(const ::std::string& __p_name, const ::Ice::Context& __ctx)
    {
        deleteDirectory(__p_name, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_deleteDirectory(const ::std::string& __p_name, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_deleteDirectory(__p_name, 0, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent));
    }
    ::Ice::AsyncResultPtr
    begin_deleteDirectory(const ::std::string& __p_name, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_deleteDirectory(__p_name, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_deleteDirectory(const ::std::string& __p_name, const ::Ice::Context& __ctx, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_deleteDirectory(__p_name, &__ctx, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_deleteDirectory(const ::std::string& __p_name, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_deleteDirectory(__p_name, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
#endif

    ::Ice::AsyncResultPtr begin_deleteDirectory(const ::std::string& __p_name)
    {
        return begin_deleteDirectory(__p_name, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_deleteDirectory(const ::std::string& __p_name, const ::Ice::Context& __ctx)
    {
        return begin_deleteDirectory(__p_name, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_deleteDirectory(const ::std::string& __p_name, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_deleteDirectory(__p_name, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_deleteDirectory(const ::std::string& __p_name, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_deleteDirectory(__p_name, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_deleteDirectory(const ::std::string& __p_name, const ::MP3Player::Callback_Player_deleteDirectoryPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_deleteDirectory(__p_name, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_deleteDirectory(const ::std::string& __p_name, const ::Ice::Context& __ctx, const ::MP3Player::Callback_Player_deleteDirectoryPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_deleteDirectory(__p_name, &__ctx, __del, __cookie);
    }

    void end_deleteDirectory(const ::Ice::AsyncResultPtr&);
    
private:

    void deleteDirectory(const ::std::string&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_deleteDirectory(const ::std::string&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    ::Ice::Int getFileLength(const ::std::string& __p_name)
    {
        return getFileLength(__p_name, 0);
    }
    ::Ice::Int getFileLength(const ::std::string& __p_name, const ::Ice::Context& __ctx)
    {
        return getFileLength(__p_name, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_getFileLength(const ::std::string& __p_name, const ::IceInternal::Function<void (::Ice::Int)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_getFileLength(__p_name, 0, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_getFileLength(const ::std::string& __p_name, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_getFileLength(__p_name, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_getFileLength(const ::std::string& __p_name, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (::Ice::Int)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_getFileLength(__p_name, &__ctx, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_getFileLength(const ::std::string& __p_name, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_getFileLength(__p_name, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
    
private:

    ::Ice::AsyncResultPtr __begin_getFileLength(const ::std::string& __p_name, const ::Ice::Context* __ctx, const ::IceInternal::Function<void (::Ice::Int)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent);
    
public:
#endif

    ::Ice::AsyncResultPtr begin_getFileLength(const ::std::string& __p_name)
    {
        return begin_getFileLength(__p_name, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_getFileLength(const ::std::string& __p_name, const ::Ice::Context& __ctx)
    {
        return begin_getFileLength(__p_name, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_getFileLength(const ::std::string& __p_name, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getFileLength(__p_name, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getFileLength(const ::std::string& __p_name, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getFileLength(__p_name, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getFileLength(const ::std::string& __p_name, const ::MP3Player::Callback_Player_getFileLengthPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getFileLength(__p_name, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getFileLength(const ::std::string& __p_name, const ::Ice::Context& __ctx, const ::MP3Player::Callback_Player_getFileLengthPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getFileLength(__p_name, &__ctx, __del, __cookie);
    }

    ::Ice::Int end_getFileLength(const ::Ice::AsyncResultPtr&);
    
private:

    ::Ice::Int getFileLength(const ::std::string&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_getFileLength(const ::std::string&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    ::std::string getFilesByRegex(const ::std::string& __p_name)
    {
        return getFilesByRegex(__p_name, 0);
    }
    ::std::string getFilesByRegex(const ::std::string& __p_name, const ::Ice::Context& __ctx)
    {
        return getFilesByRegex(__p_name, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_getFilesByRegex(const ::std::string& __p_name, const ::IceInternal::Function<void (const ::std::string&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_getFilesByRegex(__p_name, 0, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_getFilesByRegex(const ::std::string& __p_name, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_getFilesByRegex(__p_name, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_getFilesByRegex(const ::std::string& __p_name, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::std::string&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_getFilesByRegex(__p_name, &__ctx, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_getFilesByRegex(const ::std::string& __p_name, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_getFilesByRegex(__p_name, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
    
private:

    ::Ice::AsyncResultPtr __begin_getFilesByRegex(const ::std::string& __p_name, const ::Ice::Context* __ctx, const ::IceInternal::Function<void (const ::std::string&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent);
    
public:
#endif

    ::Ice::AsyncResultPtr begin_getFilesByRegex(const ::std::string& __p_name)
    {
        return begin_getFilesByRegex(__p_name, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_getFilesByRegex(const ::std::string& __p_name, const ::Ice::Context& __ctx)
    {
        return begin_getFilesByRegex(__p_name, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_getFilesByRegex(const ::std::string& __p_name, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getFilesByRegex(__p_name, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getFilesByRegex(const ::std::string& __p_name, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getFilesByRegex(__p_name, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getFilesByRegex(const ::std::string& __p_name, const ::MP3Player::Callback_Player_getFilesByRegexPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getFilesByRegex(__p_name, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getFilesByRegex(const ::std::string& __p_name, const ::Ice::Context& __ctx, const ::MP3Player::Callback_Player_getFilesByRegexPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getFilesByRegex(__p_name, &__ctx, __del, __cookie);
    }

    ::std::string end_getFilesByRegex(const ::Ice::AsyncResultPtr&);
    
private:

    ::std::string getFilesByRegex(const ::std::string&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_getFilesByRegex(const ::std::string&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    ::MP3Player::File getFile(const ::std::string& __p_name)
    {
        return getFile(__p_name, 0);
    }
    ::MP3Player::File getFile(const ::std::string& __p_name, const ::Ice::Context& __ctx)
    {
        return getFile(__p_name, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_getFile(const ::std::string& __p_name, const ::IceInternal::Function<void (const ::MP3Player::File&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_getFile(__p_name, 0, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_getFile(const ::std::string& __p_name, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_getFile(__p_name, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_getFile(const ::std::string& __p_name, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::MP3Player::File&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_getFile(__p_name, &__ctx, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_getFile(const ::std::string& __p_name, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_getFile(__p_name, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
    
private:

    ::Ice::AsyncResultPtr __begin_getFile(const ::std::string& __p_name, const ::Ice::Context* __ctx, const ::IceInternal::Function<void (const ::MP3Player::File&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent);
    
public:
#endif

    ::Ice::AsyncResultPtr begin_getFile(const ::std::string& __p_name)
    {
        return begin_getFile(__p_name, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_getFile(const ::std::string& __p_name, const ::Ice::Context& __ctx)
    {
        return begin_getFile(__p_name, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_getFile(const ::std::string& __p_name, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getFile(__p_name, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getFile(const ::std::string& __p_name, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getFile(__p_name, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getFile(const ::std::string& __p_name, const ::MP3Player::Callback_Player_getFilePtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getFile(__p_name, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getFile(const ::std::string& __p_name, const ::Ice::Context& __ctx, const ::MP3Player::Callback_Player_getFilePtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getFile(__p_name, &__ctx, __del, __cookie);
    }

    ::MP3Player::File end_getFile(const ::Ice::AsyncResultPtr&);
    
private:

    ::MP3Player::File getFile(const ::std::string&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_getFile(const ::std::string&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:
    
    ::IceInternal::ProxyHandle<Player> ice_context(const ::Ice::Context& __context) const
    {
        return dynamic_cast<Player*>(::IceProxy::Ice::Object::ice_context(__context).get());
    }
    
    ::IceInternal::ProxyHandle<Player> ice_adapterId(const ::std::string& __id) const
    {
        return dynamic_cast<Player*>(::IceProxy::Ice::Object::ice_adapterId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<Player> ice_endpoints(const ::Ice::EndpointSeq& __endpoints) const
    {
        return dynamic_cast<Player*>(::IceProxy::Ice::Object::ice_endpoints(__endpoints).get());
    }
    
    ::IceInternal::ProxyHandle<Player> ice_locatorCacheTimeout(int __timeout) const
    {
        return dynamic_cast<Player*>(::IceProxy::Ice::Object::ice_locatorCacheTimeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<Player> ice_connectionCached(bool __cached) const
    {
        return dynamic_cast<Player*>(::IceProxy::Ice::Object::ice_connectionCached(__cached).get());
    }
    
    ::IceInternal::ProxyHandle<Player> ice_endpointSelection(::Ice::EndpointSelectionType __est) const
    {
        return dynamic_cast<Player*>(::IceProxy::Ice::Object::ice_endpointSelection(__est).get());
    }
    
    ::IceInternal::ProxyHandle<Player> ice_secure(bool __secure) const
    {
        return dynamic_cast<Player*>(::IceProxy::Ice::Object::ice_secure(__secure).get());
    }
    
    ::IceInternal::ProxyHandle<Player> ice_preferSecure(bool __preferSecure) const
    {
        return dynamic_cast<Player*>(::IceProxy::Ice::Object::ice_preferSecure(__preferSecure).get());
    }
    
    ::IceInternal::ProxyHandle<Player> ice_router(const ::Ice::RouterPrx& __router) const
    {
        return dynamic_cast<Player*>(::IceProxy::Ice::Object::ice_router(__router).get());
    }
    
    ::IceInternal::ProxyHandle<Player> ice_locator(const ::Ice::LocatorPrx& __locator) const
    {
        return dynamic_cast<Player*>(::IceProxy::Ice::Object::ice_locator(__locator).get());
    }
    
    ::IceInternal::ProxyHandle<Player> ice_collocationOptimized(bool __co) const
    {
        return dynamic_cast<Player*>(::IceProxy::Ice::Object::ice_collocationOptimized(__co).get());
    }
    
    ::IceInternal::ProxyHandle<Player> ice_invocationTimeout(int __timeout) const
    {
        return dynamic_cast<Player*>(::IceProxy::Ice::Object::ice_invocationTimeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<Player> ice_twoway() const
    {
        return dynamic_cast<Player*>(::IceProxy::Ice::Object::ice_twoway().get());
    }
    
    ::IceInternal::ProxyHandle<Player> ice_oneway() const
    {
        return dynamic_cast<Player*>(::IceProxy::Ice::Object::ice_oneway().get());
    }
    
    ::IceInternal::ProxyHandle<Player> ice_batchOneway() const
    {
        return dynamic_cast<Player*>(::IceProxy::Ice::Object::ice_batchOneway().get());
    }
    
    ::IceInternal::ProxyHandle<Player> ice_datagram() const
    {
        return dynamic_cast<Player*>(::IceProxy::Ice::Object::ice_datagram().get());
    }
    
    ::IceInternal::ProxyHandle<Player> ice_batchDatagram() const
    {
        return dynamic_cast<Player*>(::IceProxy::Ice::Object::ice_batchDatagram().get());
    }
    
    ::IceInternal::ProxyHandle<Player> ice_compress(bool __compress) const
    {
        return dynamic_cast<Player*>(::IceProxy::Ice::Object::ice_compress(__compress).get());
    }
    
    ::IceInternal::ProxyHandle<Player> ice_timeout(int __timeout) const
    {
        return dynamic_cast<Player*>(::IceProxy::Ice::Object::ice_timeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<Player> ice_connectionId(const ::std::string& __id) const
    {
        return dynamic_cast<Player*>(::IceProxy::Ice::Object::ice_connectionId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<Player> ice_encodingVersion(const ::Ice::EncodingVersion& __v) const
    {
        return dynamic_cast<Player*>(::IceProxy::Ice::Object::ice_encodingVersion(__v).get());
    }
    
    static const ::std::string& ice_staticId();

private: 
    virtual ::IceProxy::Ice::Object* __newInstance() const;
};

}

}

namespace MP3Player
{

class Player : virtual public ::Ice::Object
{
public:

    typedef PlayerPrx ProxyType;
    typedef PlayerPtr PointerType;

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::Current()) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::Current()) const;
    static const ::std::string& ice_staticId();

    virtual void getInvocationCount(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___getInvocationCount(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void addFile(const ::MP3Player::File&, const ::std::string&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___addFile(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void deleteFile(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___deleteFile(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void deleteDirectory(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___deleteDirectory(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::Int getFileLength(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___getFileLength(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::std::string getFilesByRegex(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___getFilesByRegex(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::MP3Player::File getFile(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___getFile(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::DispatchStatus __dispatch(::IceInternal::Incoming&, const ::Ice::Current&);

protected:
    virtual void __writeImpl(::IceInternal::BasicStream*) const;
    virtual void __readImpl(::IceInternal::BasicStream*);
    using ::Ice::Object::__writeImpl;
    using ::Ice::Object::__readImpl;
};

inline bool operator==(const Player& l, const Player& r)
{
    return static_cast<const ::Ice::Object&>(l) == static_cast<const ::Ice::Object&>(r);
}

inline bool operator<(const Player& l, const Player& r)
{
    return static_cast<const ::Ice::Object&>(l) < static_cast<const ::Ice::Object&>(r);
}

}

namespace MP3Player
{

template<class T>
class CallbackNC_Player_getInvocationCount : public Callback_Player_getInvocationCount_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_Player_getInvocationCount(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_Player_getInvocationCountPtr
newCallback_Player_getInvocationCount(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Player_getInvocationCount<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Player_getInvocationCountPtr
newCallback_Player_getInvocationCount(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Player_getInvocationCount<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_Player_getInvocationCountPtr
newCallback_Player_getInvocationCount(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Player_getInvocationCount<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Player_getInvocationCountPtr
newCallback_Player_getInvocationCount(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Player_getInvocationCount<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_Player_getInvocationCount : public Callback_Player_getInvocationCount_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_Player_getInvocationCount(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_Player_getInvocationCountPtr
newCallback_Player_getInvocationCount(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Player_getInvocationCount<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Player_getInvocationCountPtr
newCallback_Player_getInvocationCount(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Player_getInvocationCount<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_Player_getInvocationCountPtr
newCallback_Player_getInvocationCount(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Player_getInvocationCount<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Player_getInvocationCountPtr
newCallback_Player_getInvocationCount(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Player_getInvocationCount<T, CT>(instance, 0, excb, sentcb);
}

template<class T>
class CallbackNC_Player_addFile : public Callback_Player_addFile_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_Player_addFile(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_Player_addFilePtr
newCallback_Player_addFile(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Player_addFile<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Player_addFilePtr
newCallback_Player_addFile(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Player_addFile<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_Player_addFilePtr
newCallback_Player_addFile(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Player_addFile<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Player_addFilePtr
newCallback_Player_addFile(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Player_addFile<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_Player_addFile : public Callback_Player_addFile_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_Player_addFile(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_Player_addFilePtr
newCallback_Player_addFile(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Player_addFile<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Player_addFilePtr
newCallback_Player_addFile(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Player_addFile<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_Player_addFilePtr
newCallback_Player_addFile(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Player_addFile<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Player_addFilePtr
newCallback_Player_addFile(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Player_addFile<T, CT>(instance, 0, excb, sentcb);
}

template<class T>
class CallbackNC_Player_deleteFile : public Callback_Player_deleteFile_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_Player_deleteFile(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_Player_deleteFilePtr
newCallback_Player_deleteFile(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Player_deleteFile<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Player_deleteFilePtr
newCallback_Player_deleteFile(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Player_deleteFile<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_Player_deleteFilePtr
newCallback_Player_deleteFile(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Player_deleteFile<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Player_deleteFilePtr
newCallback_Player_deleteFile(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Player_deleteFile<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_Player_deleteFile : public Callback_Player_deleteFile_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_Player_deleteFile(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_Player_deleteFilePtr
newCallback_Player_deleteFile(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Player_deleteFile<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Player_deleteFilePtr
newCallback_Player_deleteFile(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Player_deleteFile<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_Player_deleteFilePtr
newCallback_Player_deleteFile(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Player_deleteFile<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Player_deleteFilePtr
newCallback_Player_deleteFile(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Player_deleteFile<T, CT>(instance, 0, excb, sentcb);
}

template<class T>
class CallbackNC_Player_deleteDirectory : public Callback_Player_deleteDirectory_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_Player_deleteDirectory(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_Player_deleteDirectoryPtr
newCallback_Player_deleteDirectory(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Player_deleteDirectory<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Player_deleteDirectoryPtr
newCallback_Player_deleteDirectory(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Player_deleteDirectory<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_Player_deleteDirectoryPtr
newCallback_Player_deleteDirectory(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Player_deleteDirectory<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Player_deleteDirectoryPtr
newCallback_Player_deleteDirectory(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Player_deleteDirectory<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_Player_deleteDirectory : public Callback_Player_deleteDirectory_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_Player_deleteDirectory(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_Player_deleteDirectoryPtr
newCallback_Player_deleteDirectory(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Player_deleteDirectory<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Player_deleteDirectoryPtr
newCallback_Player_deleteDirectory(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Player_deleteDirectory<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_Player_deleteDirectoryPtr
newCallback_Player_deleteDirectory(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Player_deleteDirectory<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Player_deleteDirectoryPtr
newCallback_Player_deleteDirectory(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Player_deleteDirectory<T, CT>(instance, 0, excb, sentcb);
}

template<class T>
class CallbackNC_Player_getFileLength : public Callback_Player_getFileLength_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(::Ice::Int);

    CallbackNC_Player_getFileLength(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    virtual void completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::MP3Player::PlayerPrx __proxy = ::MP3Player::PlayerPrx::uncheckedCast(__result->getProxy());
        ::Ice::Int __ret;
        try
        {
            __ret = __proxy->end_getFileLength(__result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::exception(__result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::CallbackNC<T>::_callback.get()->*_response)(__ret);
        }
    }

    private:

    Response _response;
};

template<class T> Callback_Player_getFileLengthPtr
newCallback_Player_getFileLength(const IceUtil::Handle<T>& instance, void (T::*cb)(::Ice::Int), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Player_getFileLength<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Player_getFileLengthPtr
newCallback_Player_getFileLength(T* instance, void (T::*cb)(::Ice::Int), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Player_getFileLength<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_Player_getFileLength : public Callback_Player_getFileLength_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(::Ice::Int, const CT&);

    Callback_Player_getFileLength(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    virtual void completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::MP3Player::PlayerPrx __proxy = ::MP3Player::PlayerPrx::uncheckedCast(__result->getProxy());
        ::Ice::Int __ret;
        try
        {
            __ret = __proxy->end_getFileLength(__result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::exception(__result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::Callback<T, CT>::_callback.get()->*_response)(__ret, CT::dynamicCast(__result->getCookie()));
        }
    }

    private:

    Response _response;
};

template<class T, typename CT> Callback_Player_getFileLengthPtr
newCallback_Player_getFileLength(const IceUtil::Handle<T>& instance, void (T::*cb)(::Ice::Int, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Player_getFileLength<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Player_getFileLengthPtr
newCallback_Player_getFileLength(T* instance, void (T::*cb)(::Ice::Int, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Player_getFileLength<T, CT>(instance, cb, excb, sentcb);
}

template<class T>
class CallbackNC_Player_getFilesByRegex : public Callback_Player_getFilesByRegex_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(const ::std::string&);

    CallbackNC_Player_getFilesByRegex(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    virtual void completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::MP3Player::PlayerPrx __proxy = ::MP3Player::PlayerPrx::uncheckedCast(__result->getProxy());
        ::std::string __ret;
        try
        {
            __ret = __proxy->end_getFilesByRegex(__result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::exception(__result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::CallbackNC<T>::_callback.get()->*_response)(__ret);
        }
    }

    private:

    Response _response;
};

template<class T> Callback_Player_getFilesByRegexPtr
newCallback_Player_getFilesByRegex(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::std::string&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Player_getFilesByRegex<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Player_getFilesByRegexPtr
newCallback_Player_getFilesByRegex(T* instance, void (T::*cb)(const ::std::string&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Player_getFilesByRegex<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_Player_getFilesByRegex : public Callback_Player_getFilesByRegex_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const ::std::string&, const CT&);

    Callback_Player_getFilesByRegex(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    virtual void completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::MP3Player::PlayerPrx __proxy = ::MP3Player::PlayerPrx::uncheckedCast(__result->getProxy());
        ::std::string __ret;
        try
        {
            __ret = __proxy->end_getFilesByRegex(__result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::exception(__result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::Callback<T, CT>::_callback.get()->*_response)(__ret, CT::dynamicCast(__result->getCookie()));
        }
    }

    private:

    Response _response;
};

template<class T, typename CT> Callback_Player_getFilesByRegexPtr
newCallback_Player_getFilesByRegex(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::std::string&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Player_getFilesByRegex<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Player_getFilesByRegexPtr
newCallback_Player_getFilesByRegex(T* instance, void (T::*cb)(const ::std::string&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Player_getFilesByRegex<T, CT>(instance, cb, excb, sentcb);
}

template<class T>
class CallbackNC_Player_getFile : public Callback_Player_getFile_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(const ::MP3Player::File&);

    CallbackNC_Player_getFile(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    virtual void completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::MP3Player::PlayerPrx __proxy = ::MP3Player::PlayerPrx::uncheckedCast(__result->getProxy());
        ::MP3Player::File __ret;
        try
        {
            __ret = __proxy->end_getFile(__result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::exception(__result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::CallbackNC<T>::_callback.get()->*_response)(__ret);
        }
    }

    private:

    Response _response;
};

template<class T> Callback_Player_getFilePtr
newCallback_Player_getFile(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::MP3Player::File&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Player_getFile<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Player_getFilePtr
newCallback_Player_getFile(T* instance, void (T::*cb)(const ::MP3Player::File&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Player_getFile<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_Player_getFile : public Callback_Player_getFile_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const ::MP3Player::File&, const CT&);

    Callback_Player_getFile(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    virtual void completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::MP3Player::PlayerPrx __proxy = ::MP3Player::PlayerPrx::uncheckedCast(__result->getProxy());
        ::MP3Player::File __ret;
        try
        {
            __ret = __proxy->end_getFile(__result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::exception(__result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::Callback<T, CT>::_callback.get()->*_response)(__ret, CT::dynamicCast(__result->getCookie()));
        }
    }

    private:

    Response _response;
};

template<class T, typename CT> Callback_Player_getFilePtr
newCallback_Player_getFile(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::MP3Player::File&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Player_getFile<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Player_getFilePtr
newCallback_Player_getFile(T* instance, void (T::*cb)(const ::MP3Player::File&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Player_getFile<T, CT>(instance, cb, excb, sentcb);
}

}

#include <IceUtil/PopDisableWarnings.h>
#endif
