
build:
	export CLASSPATH=$CLASSPATH:./classes:/usr/share/java/ice.jar:jaudiotagger-2.0.2.jar
	javac -d classes -classpath classes:/usr/share/java/ice.jar:jaudiotagger-2.0.2.jar Server.java PlayerI.java generated/MP3Player/*.java

launch:
	java Server
